# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  #push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    #- name : Wait on tests
    #  uses: lewagon/wait-on-check-action@v0.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        - name: Wait on tests
          uses: lewagon/wait-on-check-action@master
          with:
            ref: ${{ github.ref }}
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            wait-interval: 10
            running-workflow-name: 'deploy' # HERE
    - name: install
      run: npm install
    - name: test
      run: npm run test